server:
  port: 8081
spring:
  application:
    name: delivery-product-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
#Keycloak Configuration
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: delivarius
  resource: auth-client
  public-client: true
  principal-attribute: preferred_username