spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: product_service
    password: password
    url: jdbc:mysql://127.0.0.1:3306/productservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      maximum-pool-size: 5
      data-source-properties.cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
