server:
  port: 8081
spring:
  application:
    name: delivery-product-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG