spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/delivarius
          jwk-set-uri: http://localhost:8083/auth/realms/delivarius/protocol/openid-connect/certs